---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: true
  image: rustlang/rust:nightly-slim
  commands:
  - apt-get update -y
  - apt-get install pkg-config libssl-dev ca-certificates python3 python3-pip nodejs -y
  - pip3 install cfscrape
  - cargo test

- name: sentry-release
  pull: true
  image: getsentry/sentry-cli
  commands:
  - sentry-cli releases new ${DRONE_COMMIT_SHA}
  environment:
    SENTRY_AUTH_TOKEN:
      from_secret: sentry_auth_token
    SENTRY_ORG:
      from_secret: sentry_org
    SENTRY_PROJECT:
      from_secret: sentry_project
  when:
    branch:
    - master

- name: docker
  pull: true
  image: plugins/docker
  settings:
    build_args_from_env:
    - DRONE_COMMIT_SHA
    password:
      from_secret: docker_password
    registry: registry.huefox.com
    repo: registry.huefox.com/foxbot
    tags:
    - ${DRONE_COMMIT_SHA}
    username:
      from_secret: docker_username
  when:
    branch:
    - master

- name: sentry-finalize
  image: getsentry/sentry-cli
  commands:
  - sentry-cli releases finalize ${DRONE_COMMIT_SHA}
  environment:
    SENTRY_AUTH_TOKEN:
      from_secret: sentry_auth_token
    SENTRY_ORG:
      from_secret: sentry_org
    SENTRY_PROJECT:
      from_secret: sentry_project
  when:
    branch:
    - master

- name: deploy
  pull: true
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: deploy_host
    key:
      from_secret: deploy_key
    script:
    - export VCS_REF=${DRONE_COMMIT_SHA}
    - bash /deploy/foxbot.sh
    username:
      from_secret: deploy_username
  when:
    branch:
    - master

- name: sentry-deploy
  image: getsentry/sentry-cli
  commands:
  - sentry-cli releases deploys ${DRONE_COMMIT_SHA} new -e production
  environment:
    SENTRY_AUTH_TOKEN:
      from_secret: sentry_auth_token
    SENTRY_ORG:
      from_secret: sentry_org
    SENTRY_PROJECT:
      from_secret: sentry_project
  when:
    branch:
    - master

...
