---
kind: pipeline
name: default
type: docker

steps:
- name: docker
  image: plugins/docker
  settings:
    auto_tag: true
    registry: registry.huefox.com
    repo: registry.huefox.com/foxbot
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
...
