[workspace]

members = [
    "foxbot",
    "foxbot-sites",
    "foxbot-models",
    "foxbot-utils",
    "foxbot-channel-worker",
    "foxbot-discord"
]

[profile.release]
lto = true
codegen-units = 1
