[package]
name = "foxbot"
version = "0.1.1"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json", "stream"] }
linkify = "0.4"
rand = "0.7"
regex = "1"
scraper = "0.11"
async-trait = "0.1"
fluent = "0.9"
fluent-langneg = "0.11"
unic-langid = "0.7"
hyper = "0.13"
hamming = "0.1"

sentry = { version = "0.17", features = ["with_debug_meta"] }
uuid = "0.7"
failure = "0.1"
influxdb = "0.0.6"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
envy = "0.4"

egg-mode = "0.13"
tokio = { version = "0.2", features = ["macros", "time", "stream", "sync", "signal"] }
tokio-util = { version = "0.3", features = ["codec"] }
futures = "0.3"
futures-util = "0.3"
tokio01 = { version = "0.1", package = "tokio" }

tgbotapi = { git = "https://github.com/Syfaro/tgbotapi-rs.git" }
cfscrape = { git = "https://github.com/Syfaro/cfscrape-rs.git" }
fuzzysearch = { git = "https://github.com/Syfaro/fuzzysearch-rs", features = ["trace", "local_hash"] }

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
opentelemetry = "0.1"
tracing-opentelemetry = "0.1"

rusqlite = { version = "0.21", features = ["bundled"] }
refinery = { version = "0.2", features = ["rusqlite"] }
barrel = { version = "0.6", features = ["sqlite3"] }
quaint = { version = "0.2.0-alpha.9", features = ["full"] }

rusoto_core = "0.43"
rusoto_credential = "0.43"
rusoto_s3 = "0.43"

[profile.release]
lto = true
codegen-units = 1
