[package]
name = "foxbot"
version = "0.1.1"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
linkify = "0.4"
rand = "0.7"
regex = "1"
scraper = "0.11"
async-trait = "0.1"
fluent = "0.9"
fluent-langneg = "0.11"
unic-langid = "0.7"
hyper = "0.13"
hamming = "0.1"

log = "0.4"
pretty_env_logger = "0.4"
sentry = "0.17"
uuid = "0.7"
failure = "0.1"
influxdb = { git = "https://github.com/Empty2k12/influxdb-rust.git", rev = "1b0cae12d8b1b0e2bd29129e6757a9df8a8faf50" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

egg-mode = "0.13"
tokio = { version = "0.2", features = ["macros", "time", "stream", "sync"] }
futures = "0.3"
futures-util = "0.3"
tokio01 = { version = "0.1", package = "tokio" }
pickledb = "0.4"

telegram = { path = "./telegram", features = ["trace"] }
fautil = { path = "./fautil", features = ["trace"] }
cfscrape = { git = "https://git.huefox.com/syfaro/cfscrape-rust.git" }

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
opentelemetry = "0.1"
tracing-opentelemetry = "0.1"
