[package]
name = "foxbot"
version = "0.1.1"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.0", features = ["json"] }
linkify = "0.4.0"
rand = "0.7.2"
regex = "1.3.1"
scraper = "0.11.0"
async-trait = "0.1.21"
fluent = "0.9.1"
fluent-langneg = "0.11.1"
unic-langid = "0.7.1"
hyper = "0.13.1"
hamming = "0.1.3"

log = "0.4.8"
pretty_env_logger = "0.3.1"
sentry = "0.17.0"
uuid = "0.7.4"
failure = "0.1.6"
influxdb = { git = "https://github.com/Empty2k12/influxdb-rust.git", rev = "1b0cae12d8b1b0e2bd29129e6757a9df8a8faf50" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

egg-mode = "0.13.0"
tokio = { version = "0.2.0", features = ["macros", "time", "stream"] }
futures = "0.3.1"
futures-util = "0.3.1"
tokio01 = { version = "0.1", package = "tokio" }
pickledb = "0.4.0"

telegram = { path = "./telegram" }
fautil = { path = "./fautil" }
furaffinity-rs = { git = "https://git.huefox.com/syfaro/furaffinity-rs.git" }
image = "0.22"
