[package]
name = "telegram"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { git = "https://github.com/seanmonstar/reqwest", features = ["json"] }
log = "0.4.8"
